replicaCount: 1

image:
  repository: k3d-registry:5000/server-gateway
  pullPolicy: IfNotPresent

#ports:
#  - name: http
#    containerPort: 7400
#    protocal: TCP

service:
  type: ClusterIP
  port: 6500
  targetPort: 6500


ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: localhost
      paths:
        - path: /api
          pathType: Prefix


autoscaling:
  enabled: false


nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  annotations: {}
  #name: ""
securityContext: {}
podAnnotations: {}
podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
