version: v1beta11

deployments:
  - name: may-journey-web
    helm:
      chart:
        git:
          url: https://github.com/DaddyMonster/kube-dev-test.git
          branch: main
          tag: latest
          subPath: infra/helm/may-journey-web
  - name: server-gateway
    helm:
      chart:
        git:
          url: https://github.com/DaddyMonster/kube-dev-test.git
          branch: main
          tag: latest
          subPath: infra/helm/server-gateway
  - name: ingress-nginx
    namespace: ingress-nginx
    helm:
      chart:
        name: ingress-nginx/ingress-nginx
      values:
        controller:
          metrics:
            enabled: false
            #service:
            #  annotations:
            #    prometheus.io/port: "10254"
            #    prometheus.io/scrape: "true"
            serviceMonitor:
              enabled: false
            #  additionalLabels:
            #    release: monitor
      wait: true
