version: v1beta11

images:
  #  may-base:
  #    image: localhost:4800/may-base:local
  #    cmd: [yarn, nx, run, web-journey:serve]
  #    build:
  #      buildKit:
  #        skipPush: true
  may-journey-web:
    image: localhost:4800/may-journey-web
    cmd: [yarn, nx, run, web-journey:serve]
    build:
      buildKit:
        skipPush: true
  api-gateway:
    image: localhost:4800/may-server-gateway
    cmd: [yarn, nx, run, server-gateway:serve]
    build:
      buildKit:
        skipPush: true
deployments:
  - name: may-journey-web
    helm:
      chart:
        name: ./infra/helm/may-journey-web
  - name: server-gateway
    helm:
      chart:
        name: "./infra/helm/server-gateway"


dev:
  # `dev.ports` specifies all ports that should be forwarded while `devspace dev` is running
  # Port-forwarding lets you access your application via localhost on your local machine
  ports:
    - imageSelector: localhost:4800/may-journey-web # Select the Pod that runs our `${IMAGE}`
      forward:
        - port: 6400
    - imageSelector: localhost:4800/may-server-gateway
      forward:
        - port: 6500
